# Generated by Django 5.2.7 on 2026-01-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_restpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restpassword',
            name='otp',
            field=models.CharField(max_length=255),
        ),
    ]
