# Generated by Django 5.2.7 on 2026-01-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_restpassword_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restpassword',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
