# Generated by Django 5.2.7 on 2026-01-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_passwordtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='enhance_path',
        ),
        migrations.RemoveField(
            model_name='document',
            name='original_path',
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
