# Generated by Django 5.2.7 on 2026-01-08 11:07

import server.app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_document_enhance_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=server.app.models.upload_to),
        ),
    ]
