# Generated by Django 5.2.7 on 2026-01-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_celerytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('STARTED', 'Started'), ('FINISH', 'finish'), ('FAILURE', 'Failure')], default='PENDING', max_length=20),
        ),
    ]
